id: proxy
namespace: git.demo
description: |-
  # Proxy Workflow
  PubSub からのメッセージを KVストアに保存する Proxy Workflow

  RESTエンドポイントから受け取ったメッセージをKVストアに保存し、
  job_idとanalysis_typeに基づいてイベントデータを整理します。

  ## 実行方法

  ### 実行方法1: Webhook (トリガーキー経由)
  ```
  curl -v -X POST -H 'Content-Type: application/json' \
  -d '{"job_id": "aaaaaa", "analysis_type": "type_b", "data": {"value": 40}}' \
  'http://localhost:8080/api/v1/executions/webhook/local.demo/proxy_workflow/proxy_workflow_webhook'
  ```

  ### 実行方法2: ネームスペース経由
  ```
  curl -v -X POST -H 'Content-Type: multipart/form-data' \
  -F 'message={"job_id": "aaaaaa", "analysis_type": "type_a", "data": {"value": 40}}' \
  'http://localhost:8080/api/v1/main/executions/local.demo/proxy_workflow'
  ```

triggers:
  - id: webhook_trigger
    type: io.kestra.plugin.core.trigger.Webhook
    key: proxy_workflow_webhook

tasks:
  - id: logging_start
    type: io.kestra.plugin.core.log.Log
    message:
      - "Proxy Workflow 開始"
      - "受信データ: {{trigger.body}}"

  - id: validate
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: validate_job_id
        type: io.kestra.plugin.core.flow.If
        condition: "{{ trigger.body.job_id is not defined }}"
        then:
          - id: job_id_invalid
            type: io.kestra.plugin.core.execution.Fail
            errorMessage: "メッセージにjob_idが含まれていません"

      - id: validate_analysis_type
        type: io.kestra.plugin.core.flow.If
        condition: "{{ trigger.body.analysis_type is not defined }}"
        then:
          - id: analysis_type_invalid
            type: io.kestra.plugin.core.execution.Fail
            errorMessage: "メッセージにanalysis_typeが含まれていません"

  - id: set_kv
    type: io.kestra.plugin.core.kv.Set
    namespace: local.demo
    description: 解析結果をKVストアに保存
    key: "{{trigger.body.job_id}}.{{trigger.body.analysis_type}}"
    value: "{{trigger.body}}"
    overwrite: true
    kvType: JSON
    ttl: PT24H # 24時間の有効期限

  - id: logging_result
    type: io.kestra.plugin.core.log.Log
    message:
      - "イベント保存完了: key={{trigger.body.job_id}}.{{trigger.body.analysis_type}}"
      - "KVストアへの登録が完了しました"
